module.exports=[
    {
        "question":"Which type of JavaScript language is ___",
        "option1":"Object-Oriented",
        "option2":"Object-Based",
        "option3":"Assembly-language",
        "option4":"High-level",
        "correctans":2,
    },
    {
        "question":"Which of the following is not JavaScript Data Types?",
        "option1":"Undefined",
        "option2":"Number",
        "option3":"Boolean",
        "option4":"Float",
        "correctans":4,
    },
    {
        "question":"Which company developed JavaScript?",
        "option1":"NetScape",
        "option2":"Bell Labs",
        "option3":"Sun MicroSystem",
        "option4":"IBM",
        "correctans":1,
    },
    {
        "question":"Inside which HTML element do we put the JavaScript?",
        "option1":"<script>",
        "option2":"<head>",
        "option3":"<Meta>",
        "option4":"<Style>",
        "correctans":1,
    },
    {
        "question":"Which of the following is correct about features of JavaScript?",
        "option1":"It can not Handling dates and time.",
        "option2":"JavaScript is a object-based scripting language.",
        "option3":"JavaScript is not interpreter based scripting language.",
        "option4":"All of the above",
        "correctans":2 ,
    },
    {
        "question":"Choose the correct JavaScript syntax to change the content of the following HTML code.",
        "option1":'document.getElement (“letsfindcourse").innerHTML = "I am a letsfindcourse";',
        "option2":'document.getElementById (“letsfindcourse").innerHTML = "I am a letsfindcourse";',
        "option3":'document.getId (“letsfindcourse") = "I am a letsfindcourse";',
        "option4":'document.getElementById (“letsfindcourse").innerHTML = I am a letsfindcourse;',
        "correctans": 2,
    },
    {
        "question":"Which of the following is the correct syntax to display 'Letsfindcourse' in an alert box using JavaScript?",
        "option1":'alert-box("Letsfindcourse");',
        "option2":'confirm("Letsfindcourse");',
        "option3":'msgbox("Letsfindcourse");',
        "option4":'alert("Letsfindcourse");',
        "correctans": 4,
    },
    {
        "question":'What is the correct syntax for referring to an external script called "LFC.js"',
        "option1":'<script src="LFC.js">',
        "option2":'<script source="LFC.js">',
        "option3":'<script ref="LFC.js">',
        "option4":'<script type="LFC.js">',
        "correctans": 1,
    },
    {
        "question":"Which of the following is not Javascript frameworks or libraries?",
        "option1":"Polymer",
        "option2":"Meteor",
        "option3":"Cassandra",
        "option4":"jQuery",
        "correctans": 3,
    },
    {
        "question":"Why so JavaScript and Java have similar name?",
        "option1": " JavaScript is a stripped-down version of Java",
        "option2":"JavaScript's syntax is loosely based on Java's",
        "option3":"They both originated on the island of Java",
        "option4":"None of the above",
        "correctans":2,
    }
  ]